services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-java-app
    ports:
      - "8080:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/backend-java
      KEYCLOAK_CLIENT_ID: game-backend
      KEYCLOAK_REQUIRED_AUDIENCE: game-backend
      KEYCLOAK_ALLOWED_AUTHORIZED_PARTIES: game-backend-cli

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8090:8080"
    command: start-dev --http-port=8080 --import-realm
    volumes:
      - ./docker/keycloak/realm-import:/opt/keycloak/data/import:ro
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/8080'"]
      interval: 10s
      timeout: 5s
      retries: 20
