origins: http://localhost:4200,http://localhost:7080

server:
  error:
    include-message: always
  ssl:
    enabled: false

spring:
  profiles:
    active: secrets
  application:
    name: order-taking-api
  rabbitmq:
    host: localhost
    port: 5672
    username: ${secret.rabbitmq.username}
    password: ${secret.rabbitmq.password}

# See https://github.com/ch4mpy/spring-addons/blob/master/samples/webmvc-jwt-default
com:
  c4-soft:
    springaddons:
      oidc:
        cors:
          - path: /**
            allowed-origin-patterns: ${origins}
        ops:
          - iss: http://localhost:8442/auth/realms/baeldung-keycloak
            username-claim: preferred_username
            authorities:
              - path: $.realm_access.roles
              - path: $.resource_access.*.roles
        resourceserver:
          permit-all:
            - /no-op
            - /greet/public
            - /actuator/health/readiness
            - /actuator/health/liveness
            - /v3/api-docs/**
# Logging
logging:
  level:
    org:
      springframework: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

#---
#scheme: https
#keycloak-port: 8443
#
#server:
#  ssl:
#    enabled: true
#
#spring:
#  config:
#    activate:
#      on-profile: ssl