spring:
  profiles:
    active: secrets
  application:
    name: order-taking-api
  security:
    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${secret.oauth.google.client-id}
#            client-secret: ${secret.oauth.google.client-secret}
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            scope:
#              - email
#              - profile
#              - openid
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/master
          jwk-set-uri: http://localhost:8081/auth/realms/master/protocol/openid-connect/certs
  docker.compose.enabled: false
  datasource:
    url: ${secret.datasource.url}
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${secret.rabbitmq.username}
    password: ${secret.rabbitmq.password}

  mvc:
    # Development only
    log-request-details: true

# Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: debug
        security.oauth2.client: debug
        web: debug
        boot: info
