spring:
  application:
    name: game-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/backend-java}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: info
        web: info
        boot: info

app:
  security:
    keycloak:
      client-id: ${KEYCLOAK_CLIENT_ID:game-backend}
      required-audience: ${KEYCLOAK_REQUIRED_AUDIENCE:game-backend}
      allowed-authorized-parties: ${KEYCLOAK_ALLOWED_AUTHORIZED_PARTIES:game-backend-cli}
      principal-claim: ${KEYCLOAK_PRINCIPAL_CLAIM:preferred_username}
