spring:
  application:
    name: order-taking-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/backend-java}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Logging
logging:
  level:
    root: info
    org:
      springframework:
        security: info
        web: info
        boot: info

app:
  security:
    keycloak:
      client-id: ${KEYCLOAK_CLIENT_ID:order-taking-api}
      required-audience: ${KEYCLOAK_REQUIRED_AUDIENCE:order-taking-api}
      allowed-authorized-parties: ${KEYCLOAK_ALLOWED_AUTHORIZED_PARTIES:order-taking-api-cli}
      principal-claim: ${KEYCLOAK_PRINCIPAL_CLAIM:preferred_username}
